'use strict';
(()=>{
const B=window.B,$=B.$,$$=B.$$,A=window.BOLSILLO_ASSETS; A.portrait=A.portrait||A.natural; A.room=A.room||A.hoodie;
B.filter='all';B.kind='expense';
const lookMap={natural:{name:'Natural',xp:0,img:A.natural},hoodie:{name:'Hoodie',xp:180,img:A.hoodie}};
const catIcon=c=>({Comida:'◒',Transporte:'↗',Casa:'⌂',Trabajo:'⌁',Diversión:'✦',Salud:'＋',Compras:'◇',Educación:'⌘',Otros:'•'}[c]||'•');
const show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
const mask=()=>{const p=B.S.profile.privacy;$$('.money').forEach(e=>e.classList.toggle('masked',p));$('privacyToggle').textContent=p?'◌':'◉'};
function go(id){$$('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));$$('.bottom-nav [data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='milo')renderMilo();if(id==='goals')renderGoals();if(id==='activity')renderActivity();if(id==='profile')renderProfile()}
function renderHome(){const cm=B.month(),ws=B.weekSummary(),score=B.score(),alias=B.S.profile.alias||'TU';$('hello').textContent=`HOLA, ${alias.toUpperCase()}`;$('helloName').innerHTML=cm.income>0?'Tu dinero.<br>Bajo control.':'Tu dinero.<br>Sin ruido.';$('available').textContent=B.money(cm.available);$('monthHint').textContent=cm.income?`${B.money(cm.income)} de ingreso total este mes`:'Configura tu ingreso mensual para empezar.';$('heroSpendText').textContent=`${B.money(cm.spent)} de ${B.money(B.S.profile.budget)}`;const pct=B.clamp(cm.ratio*100,0,100);$('budgetBar').style.width=pct+'%';$('budgetPct').textContent=Math.round(pct)+'%';const mood=B.petMood();$('miloHello').textContent=(B.S.pet.name||'Milo')+' te espera';$('miloMood').textContent=mood.text;$('homeMilo').src=currentLookImg();$('navMilo').src=currentLookImg();const d=B.weekDelta();if(d.prev&&d.delta!==0){$('insightTitle').textContent=d.delta>0?'Vas mejor que la semana pasada':'Esta semana pide atención';$('insightText').textContent=`${d.delta>0?'+':''}${d.delta} puntos de disciplina frente a la semana anterior.`}else if(ws.expense.length){$('insightTitle').textContent=ws.planned>=.8?'Vas con intención':'Hay gastos que te están sorprendiendo';$('insightText').textContent=ws.planned>=.8?'La mayoría de tus gastos de esta semana fueron planeados.':'Marca como planeados los gastos que ya esperabas; el score mide control.'}else{$('insightTitle').textContent='Empieza esta semana';$('insightText').textContent='Registra algo y Bolsillo empezará a leer tu ritmo.'}const start=B.ws();$('weekRange').textContent=`${B.fmt(start)} — ${B.fmt(B.add(start,6))}`;renderWeekChart(start);$('score').textContent=score;$('scoreRing').style.background=`conic-gradient(var(--accent) ${score*3.6}deg,#302f2b 0deg)`;$('weekSpent').textContent=B.money(ws.spent)+' esta semana';$('streak').textContent=B.streak()+' días de racha';renderCategories(cm);renderGoalSpotlight();mask()}
function renderWeekChart(start){const days=['L','M','M','J','V','S','D'],vals=[];for(let i=0;i<7;i++){const d=B.add(start,i);vals.push(B.S.transactions.filter(t=>t.k==='expense'&&t.d===d).reduce((a,t)=>a+t.a,0))}const max=Math.max(1,...vals),today=B.today();$('weekChart').innerHTML=vals.map((v,i)=>{const date=B.add(start,i),h=Math.max(v?12:5,v/max*100);return `<div class="daycol ${date===today?'current':''}"><i style="height:${h}%"></i><span>${days[i]}</span></div>`}).join('')}
function renderCategories(cm){const rows=cm.categories.slice(0,5);$('categoryList').innerHTML=rows.length?rows.map(([c,v])=>{const share=cm.spent?Math.round(v/cm.spent*100):0;return `<div class="category-row"><span class="cat-dot">${catIcon(c)}</span><div><b>${B.esc(c)}</b><small>${share}% de tus gastos</small></div><strong class="money">${B.money(v)}</strong></div>`}).join(''):`<div class="empty">Tus categorías aparecerán aquí cuando registres gastos.</div>`}
function renderGoalSpotlight(){const g=B.S.goals[0];if(!g){$('goalTitle').textContent='Ponle nombre a tu siguiente victoria.';$('goalCopy').textContent='Tu ahorro necesita destino, no culpa.';$('goalBar').style.width='0%';return}const p=B.goalProgress(g);$('goalTitle').textContent=`${g.emoji} ${g.name}`;$('goalCopy').textContent=`${Math.round(p)}% completado · ${B.goalEta(g)}`;$('goalBar').style.width=p+'%'}
function currentLook(){return lookMap[B.S.pet.look]||lookMap.natural}function currentLookImg(){return B.S.pet.look==='natural'||!B.S.pet.look?A.portrait:currentLook().img}
function renderActivity(){const cm=B.month();$('monthSpend').textContent=B.money(cm.spent);$('plannedPct').textContent=Math.round(cm.planned*100)+'%';$('txCount').textContent=cm.tx.length;const all=[...B.S.transactions].sort((a,b)=>b.d.localeCompare(a.d));const rows=all.filter(t=>B.filter==='all'||t.k===B.filter).slice(0,100);$('txList').innerHTML=rows.length?rows.map(t=>`<article class="tx-item"><span class="tx-icon">${t.k==='income'?'＋':catIcon(t.c)}</span><div><h3>${B.esc(t.n||t.c)}</h3><p>${B.esc(t.c)} · ${B.fmt(t.d)}${t.k==='expense'?(t.planned?' · planeado':' · impulso'):''}</p></div><div class="tx-amount"><b class="money">${t.k==='income'?'+':'−'}${B.money(t.a)}</b><button type="button" data-delete-tx="${B.esc(t.id)}" aria-label="Borrar">×</button></div></article>`).join(''):`<div class="empty">Aún no hay movimientos. Registrar el primero toma unos segundos.</div>`;$$('[data-delete-tx]').forEach(b=>b.onclick=()=>{if(confirm('¿Borrar este movimiento?')){B.S.transactions=B.S.transactions.filter(t=>t.id!==b.dataset.deleteTx);B.save();renderAll()}});mask()}
function renderMilo(){const l=B.level();$('miloName').textContent=B.S.pet.name||'Milo';$('leafCount').textContent=B.S.pet.leaves;$('miloLevel').textContent=l.level;const p=B.clamp((B.S.xp-l.base)/(l.next-l.base)*100,0,100);$('levelBar').style.width=p+'%';$('levelXP').textContent=`${B.S.xp} / ${l.next} XP`;$('miloFed').textContent=`${B.S.pet.fed} snacks`;const checked=B.S.checkins.includes(B.today());$('missionTitle').textContent=checked?'Misión cumplida':'Revisa tu día';$('missionCopy').textContent=checked?'Milo ya sabe que hoy miraste tus cuentas.':'Una mirada consciente vale más que veinte gráficos.';$('missionReward').textContent=checked?'✓':'+15 XP';$('checkinBtn').querySelector('span').textContent=checked?'Revisado':'Revisé hoy';$('wardrobe').innerHTML=Object.entries(lookMap).map(([id,o])=>{const locked=B.S.xp<o.xp,selected=(B.S.pet.look||'natural')===id;return `<button class="look-card ${locked?'locked':''} ${selected?'selected':''}" data-look="${id}" type="button"><img src="${o.img}" alt="Milo ${B.esc(o.name)}"><span>${B.esc(o.name)}</span><small>${locked?`Nivel · ${o.xp} XP`:'Desbloqueado'}</small><i>${selected?'✓':locked?'⌁':'+'}</i></button>`}).join('');$$('[data-look]').forEach(btn=>btn.onclick=()=>{const o=lookMap[btn.dataset.look];if(B.S.xp<o.xp){B.toast(`Se desbloquea con ${o.xp} XP.`);return}B.S.pet.look=btn.dataset.look;B.save();renderAll();B.toast(`${o.name} equipado.`)})}
function renderGoals(){const gs=B.S.goals;$('futureSymbol').textContent=gs[0]?.emoji||'◎';if(gs[0]){$('futureTitle').textContent=gs[0].name;$('futureText').textContent=`${Math.round(B.goalProgress(gs[0]))}% listo · ${B.goalEta(gs[0])}`}else{$('futureTitle').textContent='Todavía no elegiste destino.';$('futureText').textContent='Una meta concreta convierte sacrificios en decisiones.'}$('goalsList').innerHTML=gs.length?gs.map(g=>{const p=B.goalProgress(g),cur=B.goalCurrent(g);return `<article class="goal-card"><div class="goal-card-head"><span>${g.emoji}</span><div><h3>${B.esc(g.name)}</h3><p>${B.goalEta(g)}</p></div><button type="button" data-contrib="${B.esc(g.id)}">+ Aportar</button></div><div class="goal-track"><i style="width:${p}%"></i></div><div class="goal-card-foot"><span class="money">${B.money(cur)} / ${B.money(g.target)}</span><b>${Math.round(p)}%</b></div></article>`}).join(''):`<div class="empty">Crea una meta concreta: fondo de emergencia, viaje, laptop, casa…</div>`;$$('[data-contrib]').forEach(b=>b.onclick=()=>openContribution(b.dataset.contrib));mask()}
function renderProfile(){const p=B.S.profile;$('alias').value=p.alias;$('petName').value=B.S.pet.name;$('income').value=p.income||'';$('budget').value=p.budget||'';$('savingRate').value=p.savingsRate;$$('.theme-pick').forEach(b=>b.classList.toggle('active',b.dataset.theme===p.theme))}
function renderAll(){document.querySelectorAll('[data-asset=portrait]').forEach(e=>e.src=A.portrait);document.querySelectorAll('[data-asset=room]').forEach(e=>e.src=A.room);document.documentElement.dataset.theme=B.S.profile.theme||'black';B.syncAwards();renderHome();if(!$('activity').classList.contains('hidden'))renderActivity();if(!$('milo').classList.contains('hidden'))renderMilo();if(!$('goals').classList.contains('hidden'))renderGoals();if(!$('profile').classList.contains('hidden'))renderProfile()}
function openTx(kind='expense'){B.kind=kind;show('txModal');$('txAmount').value='';$('txNote').value='';$('txDate').value=B.today();$('txPlanned').checked=true;$$('#txModal [data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));$('plannedWrap').style.display=kind==='expense'?'grid':'none';setTimeout(()=>$('txAmount').focus(),100)}
function openContribution(id){const g=B.S.goals.find(x=>x.id===id);if(!g)return;$('contribId').value=id;$('contribTitle').textContent=g.name;$('contribAmount').value='';$('contribDate').value=B.today();show('contribModal')}
function weeklyStory(){const c=$('storyCanvas'),x=c.getContext('2d'),s=B.weekSummary(),league=B.league(),alias=B.S.profile.alias||'MI SEMANA',g=B.S.goals[0];x.clearRect(0,0,c.width,c.height);x.fillStyle='#0a0a09';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#3a332b';x.lineWidth=3;x.strokeRect(72,72,936,1776);x.fillStyle='#e5c99f';x.font='700 38px Arial';x.fillText('BOLSILLO',96,135);x.fillStyle='#f5efe7';x.font='500 92px Georgia';x.fillText(alias.toUpperCase(),96,295);x.font='500 92px Georgia';x.fillText('ESTA SEMANA',96,392);x.fillStyle='#9f988f';x.font='30px Arial';x.fillText('Disciplina que se ve. Dinero que no se presume.',96,458);x.fillStyle='#e5c99f';x.font='700 210px Arial';x.fillText(String(s.score),96,760);x.fillStyle='#f5efe7';x.font='38px Arial';x.fillText('/100 CONTROL',490,760);x.strokeStyle='#403a32';x.beginPath();x.moveTo(96,840);x.lineTo(984,840);x.stroke();x.font='700 34px Arial';x.fillStyle='#f5efe7';x.fillText(`${league.name.toUpperCase()}  ·  ${B.S.xp} XP`,96,930);x.fillStyle='#9f988f';x.font='29px Arial';x.fillText(`${s.streak} días de racha`,96,990);x.fillText(`${Math.round(s.planned*100)}% de gastos planeados`,96,1040);if(g)x.fillText(`${Math.round(B.goalProgress(g))}% de ${g.name}`,96,1090);x.fillStyle='#e5c99f';x.font='italic 54px Georgia';wrap(x,B.story(),96,1280,850,68);x.fillStyle='#f5efe7';x.font='700 30px Arial';x.fillText('MI DINERO NO SE COMPARTE.',96,1672);x.fillStyle='#9f988f';x.font='28px Arial';x.fillText('MI DISCIPLINA SÍ.',96,1718);show('storyModal')}
function wrap(ctx,text,x,y,max,line){const words=text.split(' ');let cur='';for(const w of words){const t=cur+w+' ';if(ctx.measureText(t).width>max&&cur){ctx.fillText(cur,x,y);cur=w+' ';y+=line}else cur=t}ctx.fillText(cur,x,y)}
function downloadStory(){const c=$('storyCanvas');c.toBlob(async blob=>{if(!blob)return;const f=new File([blob],'bolsillo-semana.png',{type:'image/png'});try{if(navigator.share&&navigator.canShare?.({files:[f]})){await navigator.share({files:[f],title:'Mi semana en Bolsillo'});return}}catch{}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('privacyToggle').onclick=()=>{B.S.profile.privacy=!B.S.profile.privacy;B.save();renderAll()};$('quickExpense').onclick=()=>openTx('expense');$('quickIncome').onclick=()=>openTx('income');$('addTxTop').onclick=()=>openTx('expense');$('shareWeekly').onclick=weeklyStory;$('downloadStory').onclick=downloadStory;
$$('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)hide(m.id)}));$$('#txModal [data-kind]').forEach(b=>b.onclick=()=>{B.kind=b.dataset.kind;$$('#txModal [data-kind]').forEach(x=>x.classList.toggle('active',x===b));$('plannedWrap').style.display=B.kind==='expense'?'grid':'none'});
$('txForm').onsubmit=e=>{e.preventDefault();const a=Number($('txAmount').value);if(!Number.isFinite(a)||a<=0)return;B.S.transactions.push({id:B.id(),k:B.kind,a,c:B.kind==='income'?'Ingresos':$('txCategory').value,n:$('txNote').value.trim()||$('txCategory').value,d:$('txDate').value||B.today(),planned:B.kind==='expense'?$('txPlanned').checked:true});B.S.xp+=10;B.S.pet.leaves+=B.kind==='expense'?0:1;B.save();hide('txModal');renderAll();B.toast('Movimiento guardado.')};
$('feedMilo').onclick=()=>{if(B.S.pet.leaves<1){B.toast('Necesitas 1 corazón. Revísate hoy o sigue avanzando.');return}B.S.pet.leaves--;B.S.pet.fed++;B.S.xp+=4;B.save();renderAll();B.toast(`${B.S.pet.name} está feliz.`)};$('playMilo').onclick=()=>B.toast(`${B.S.pet.name} jugó contigo. Aquí no hay castigos por no entrar.`);$('wardrobeBtn').onclick=()=>document.querySelector('.wardrobe').scrollIntoView({behavior:'smooth'});$('checkinBtn').onclick=()=>{if(B.addCheck()){B.save();renderAll();B.toast('Día revisado · +15 XP')}else B.toast('Hoy ya hiciste tu revisión.')};
$('addGoal').onclick=()=>{show('goalModal');$('goalName').value='';$('goalTarget').value='';$('goalMonthly').value=''};$('goalForm').onsubmit=e=>{e.preventDefault();const target=Number($('goalTarget').value);if(target<=0)return;B.S.goals.push({id:B.id(),name:$('goalName').value.trim(),emoji:$('goalEmoji').value,target,monthly:Math.max(0,Number($('goalMonthly').value)||0),due:'',contribs:[]});B.S.xp+=25;B.save();hide('goalModal');renderAll();B.toast('Meta creada.')};$('contribForm').onsubmit=e=>{e.preventDefault();const g=B.S.goals.find(x=>x.id===$('contribId').value),a=Number($('contribAmount').value);if(!g||a<=0)return;g.contribs.push({id:B.id(),a,d:$('contribDate').value||B.today()});B.S.xp+=20;B.S.pet.leaves+=1;B.save();hide('contribModal');renderAll();B.toast('Aporte registrado · +20 XP')};
$('saveProfile').onclick=()=>{B.S.profile.alias=$('alias').value.trim();B.S.pet.name=$('petName').value.trim()||'Milo';B.S.profile.income=Math.max(0,Number($('income').value)||0);B.S.profile.budget=Math.max(1,Number($('budget').value)||500);B.S.profile.savingsRate=B.clamp(Number($('savingRate').value)||0,0,90);B.save();renderAll();B.toast('Configuración guardada.')};$$('.theme-pick').forEach(b=>b.onclick=()=>{B.S.profile.theme=b.dataset.theme;B.save();renderAll()});
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify({app:'Bolsillo',version:7,exportedAt:new Date().toISOString(),data:B.S},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bolsillo-backup-${B.today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('importData').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=JSON.parse(await f.text()),n=B.normalize(r.data||r);if(!confirm(`Importar ${n.transactions.length} movimientos y reemplazar los datos actuales?`))return;B.S=n;B.save();renderAll();go('home');B.toast('Respaldo importado.')}catch{B.toast('Archivo no válido.')}e.target.value=''};$('eraseData').onclick=()=>{if(confirm('¿Borrar todos los datos de Bolsillo en este navegador?')){B.S=B.blank();B.save();renderAll();go('home');B.toast('Datos borrados.')}};
$$('#txFilters [data-filter]').forEach(b=>b.onclick=()=>{B.filter=b.dataset.filter;$$('#txFilters [data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderActivity()});
window.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal').forEach(m=>m.classList.add('hidden'))});
renderAll();go('home');
})();
